midtermregodon/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
]

post/urls.py
from django.urls import path
from . import views
app_name = "post"

urlpatterns = [
    path('',views.index, name = 'index'),
    path('<int:question_id>/', views.details, name = 'details'),
    path('<int:question_id>/update/', views.update, name = 'update'),
    path('create/', views.create, name = 'create'),
    path('<int:question_id>/comment/', views.update, name = 'comment'),
]

post/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length = 100)
    date_created = models.DateTimeField('Date Created', default=datetime.now)
    date_updated = models.DateTimeField('Date Updated', default=datetime.now)
    content = models.TextField(max_length = 100)
    #is_active = False

    def __str__(self):
        return 'Post: {}'.format(self.title)


class Comment(models.Model):
    date_created =  models.DateTimeField('Date Created', default=datetime.now)
    content = models.TextField(max_length = 100)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comments')

    def __str__(self):
        return 'Comment: {}'.format(self.content)

post/forms.py
from django.forms import ModelForm
from .models import Post
from .models import Comment


class CreatePostModelForm(ModelForm):
    class Meta:
        model = Post
        #fields = ['question_text','pub_date']
        #include
        exclude = ['id', 'date_modified']

class CommentModelForm(ModelForm):
    class Meta:
        model = Comment
        #fields = ['question_text','pub_date']
        #include
        exclude = ['id']

post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from .forms import CreatePostModelForm
from .forms import CommentModelForm
from datetime import datetime
from django.shortcuts import redirect

# Create your views here.


def index(request):
	context = {}
	post = Post.objects.all()
	context['posts'] = post
	return render(request, 'index.html', context)

def details (request, post_id):
	context = {}
	context['posts'] = Post.objects.get(id=post_id)
	return render(request, 'details.html', context)

def update (request,post_id):
	post = Post.objects.get(id = post_id)
	context['form'] = PostModelForm(initial={'date_updated': datetime.now})

	if request.method == 'POST':
		form = PostModelForm(request.POST, instance=post)
		if form.is_Valid():
			form.save()
			return HttpResponse('Post updated')
		else:
			context['form'] = form
			render(request, 'update.html', context)
	else:
		context['form'] = QuestionModelForm(instance = post)
	return render(request, 'update.html', context)

def create(request):
	context = {}
	context['form'] = CreatePostModelForm(initial={'date_created': datetime.now})

	if request.method == "POST":
		form = CreatePostModelForm(request.POST)
		
		if form.is_valid():
			form.save()
			return redirect('/post/')
		else:
			context['form'] = form
			return render(request, 'create.html', context)
	else:
		return render(request, 'create.html', context)


def comment(request):
	context = {}
	context['form'] = CommentModelForm(initial={'date_created': datetime.now})

	if request.method == "POST":
		form = CommentnModelForm(request.POST)
		
		if form.is_valid():
			form.save()
			#form.pub_date = datetime.now()
			#form.save()
			return redirect('/post/')
		else:
			context['form'] = form
			return render(request, 'comment.html', context)
	else:
		return render(request, 'comment.html', context)

post/templates/base.html
{% load static %}

<html>
    <head>
        <title>
            {% block head %}
                this is the title head
            {% endblock %}

        

        </title>
        <link rel='stylesheet' type = 'text/css' href ='{% static "post/materialize/css/materialize.min.css" %}' >
        {% block styles %}
        {% endblock %}
        <style>
        div {
        padding: 100px;
        border: 0px solid #4CAF50;
        }
        </style>
    </head>
    
    <body>
        <div>
        {% block body %}
            
        {% endblock body %}
        
        </div>
        <script src ='{% static "polls/materialize/js/materialize.min.js" %}'> </script>
        {% block scripts %}
        {% endblock scripts %}
    
    </body>
</html>

post/templates/comment.html
{% extends 'base.html' %}


{% block head %}
    this is the comment page

{% endblock head %}

{% block body %}
    <form action="{% url 'polls:comment' %}" method="POST">
    {% csrf_token %}
    {% for field in form %}
        {{ field.label}} {{ field }}
    {% endfor %}

    <input type="submit" value = "Add Comment">
    
{% endblock body %}

post/templates/create.html
{% extends 'base.html' %}


{% block head %}
    this is the create page

{% endblock head %}

{% block body %}
    <form action="{% url 'post:create' %}" method="POST">
    {% csrf_token %}

    {% for field in form %}
        {{ field.label}} {{ field }}
    {% endfor %}



    <input type="submit" value = "Create">
    
{% endblock body %}

post/templates/detail.html
{% extends 'base.html' %}

{% block head %}
this is the detail page
{% endblock head %}

{% block body %}

    {{ post.title }}
    {{ post.date_created }}
    {{ post.content }}


    <form action="{% url 'post:comment' %}" method="POST">
        {% csrf_token %}
    <input type="submit" value = "Comment">
    <form action="{% url 'post:update' %}" method="POST">
        {% csrf_token %}
    <input type="submit" value = "Update">

    <br />
    comment:
    <br />

    {% for comment in post.comments.all %}
        {{comment.content}}<br />

{% endfor %}

{% endblock body %}

post/templates/index.html
{% extends 'base.html' %}

{% block head %}
{% endblock head %}


{% block body %}

    <form action="{% url 'post:create' %}" method="POST">
        {% csrf_token %}
    <input type="submit" value = "Create a new post">

    <ol>
    {% for post in posts %}    
        <li>
        <a href = '{% url "post:detail" post.id %}'> Question: {{ post.title }} </a><br />
    </li>
    {% endfor %}
    </ol>

{% endblock body %}

post/templates/update.html
{% extends 'base.html' %}

{% block head %}
    this is the update page

{% endblock head %}
{% block body %}
    <form action="{% url 'post:update' form.instance.id %}" method="POST">
    {% csrf_token %}

    {% for field in form %}
        {{ field.label }} {{ field }}
    {% endfor %}




    <input type="submit" value = "Update"
{% endblock body %}